puzzle/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'solver/$', views.solver, name='solver'),
    url(r'engine/$', views.SudokuEngineView.as_view(), name='engine')
]

sudoku_trainer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^puzzle/', include('puzzle.urls', namespace='puzzle', app_name='puzzle'))
]

puzzle/models.py
from django.db import models

# Create your models here.

puzzle/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from engine.engine import Puzzle
from rest_framework import status
from rest_framework.decorators import parser_classes
from rest_framework.parsers import JSONParser


@parser_classes([JSONParser])
class SudokuEngineView(APIView):
    def post(self, request, *args, **kwargs):
        """ get the filled cells, solve the puzzle, return the steps """
        filled_cells = request.data
        grid = []
        for cell in filled_cells:
            grid.append((int(cell['x']), cell['y'], cell['v']))
        puzzle = Puzzle(grid)
        puzzle.solve()
        result = puzzle.steps
        return Response(result, status=status.HTTP_200_OK)


def solver(request):
    return render(request, 'puzzle/puzzle_page.html', {'filled_cells': []})

sudoku_trainer/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {})

puzzle/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'scss/style.css' %}">
    {% block additional_statics %}
    {% endblock %}
</head>
<body>
    <noscript>Sorry, but this site needs JavaScript to function. Please turn on JavaScript in your browser.</noscript>
    <header>
        <nav id="main_nav">
           <div id="masthead">
               <div id="logo"><a href="{% url 'index' %}">Sudoku</a></div>
                <div id="hamburger"></div>
            </div>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'puzzle:solver' %}">Solve</a></li>
                <li><a href="#">Challenge</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block body %}
        {% endblock %}
    </main>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block additional_js %}
    {% endblock %}
</body>
</html>

puzzle/templates/index.html
{% extends 'base.html' %}
{% block title %}Sudoku Trainer{% endblock %}

{% block body %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis ut turpis vel vestibulum. Aliquam sem velit, lacinia eu accumsan pharetra, blandit id risus. Sed ultricies egestas blandit. Suspendisse tempor metus quis purus ultricies, et ultricies tellus aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec laoreet ante vitae malesuada luctus. Nulla id rutrum risus, a tincidunt neque. Maecenas hendrerit velit non rutrum vehicula.
{% endblock %}

puzzle/templates/puzzle/grid.html
{% load show_grid %}
<table class="grid">
    <tr>
        <th> </th>
        <th>A</th>
        <th>B</th>
        <th>C</th>
        <th>D</th>
        <th>E</th>
        <th>F</th>
        <th>G</th>
        <th>H</th>
        <th>I</th>
    </tr>
    {% for y in numbers %}
        <tr id="row-{{y}}">
            <th>{{ y|row_num }}</th>
            {% autoescape off %}
                {% for x in numbers %}
                    {% show_cell x y %}
                {% endfor %}
            {% endautoescape %}
        </tr>
    {% endfor %}
</table>

puzzle/templates/puzzle/puzzle_page.html
{% extends 'base.html' %}
{% load show_grid %}
{% block additional_statics %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'puzzle/grid.css' %}">
{% endblock %}

{% block body %}
{% show_grid %}
<div id="steps_container">
    <header>Solution</header>
   <button type="button" id="solve">Solve</button>
    <div id="step_text"></div>
    <div id="steps_nav">
        <button type="button" id="steps_prev">Previous</button>
        <button type="button" id="show_comp">Show Complete Solution</button>
        <button id="steps_next" type="button">Next</button>
    </div>
</div>
{% endblock %}

{% block additional_js %}
<script src="{% static 'puzzle/puzzle.js' %}"></script>
{% endblock %}